### ISSUE TITLE
[网站显示 BUG] 鼠标放在导航栏上，导航栏移动的 BUG

### ISSUE THREAD

**Issue by boh5** [xiaolincoder/CS-Base#49]
### 问题：
鼠标放在 `图解 MySQL` 和 `图解 Redis` 两个 nav 上的时候，整个前面的导航条目(包括搜索框) 都会向左移动，放在其他 nav 上没有这个问题。
### 截图：
![](https://i.imgur.com/KlLtgIV.png)
### 环境：
操作系统：windows 10
屏幕分辨率：1920 * 1080
浏览器：Chrome [版本 103.0.5060.114（正式版本） （32 位）]

**Comment by xiaolincoder** [comment]
我这边好像没有这个问题也。。

**Comment by foxwhite25** [comment]
能够复现，主要原因是因为 `.nav_item` 并没有设置宽度，并且在`hover`的时候 `font-weight:bold` ，英文字的宽度变宽了。

解决的方法也有很多，你可以加个 `letter-spacing` ，或者加个 `before` 相同内容的 `pseudo element` 来固定宽度，并且隐藏。

```css
a::before {
    display: block;
    content: attr(title);
    font-weight: bold;
    height: 0;
    overflow: hidden;
    visibility: hidden;
}
```
```html
<a href="#" title="图解 Redis">图解 Redis</a>
```
